package com.zamaflow.employee_rewards;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Award implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "AWARD_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "AWARD_ID_SEQ", name = "AWARD_ID_GENERATOR")
    private java.lang.Long id;

    public Award() {
    }
    
    public Award(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}